
[[constraint]]
  name = "github.com/urfave/cli"
  branch = "v1"

[[constraint]]
  name = "github.com/koron/go-dproxy"
  version = "v1.1"

[[constraint]]
  name = "github.com/BurntSushi/toml"
  version = "v0.3.0"

[[constraint]]
  branch = "master"
  name = "github.com/aws/aws-sdk-go/aws/..."

[[constraint]]
  branch = "17.05.x"
  name = "github.com/docker/docker/..."

[[constraint]]
  branch = "master"
  name = "github.com/tcnksm/go-latest"
