
[[constraint]]
  name = "github.com/urfave/cli"
  branch = "v1"

[[constraint]]
  name = "github.com/koron/go-dproxy"
  version = "v1.1"

[[constraint]]
  name = "github.com/BurntSushi/toml"
  version = "v0.3.0"

[[constraint]]
  branch = "master"
  name = "github.com/aws/aws-sdk-go/aws/..."

[[constraint]]
  name = "github.com/docker/docker"
  version = "=v17.05.0-ce"

[[constraint]]
  branch = "master"
  name = "github.com/tcnksm/go-latest"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.1.4"

[[constraint]]
  name = "github.com/stvp/rollbar"
  version = "v0.5.0"

# depends on docker v17.05.0-ce (only prone to error)
[[override]]
  revision = "5d4e5de2f9962c2de8a7872128e2cc09dfdd99aa"
  name = "github.com/docker/libnetwork"

[[override]]
  name = "github.com/opencontainers/runc"
  revision =  "9c2d8d184e5da67c95d601382adf14862e4f2228"

[[override]]
  name = "github.com/docker/distribution"
  revision =  "b38e5838b7b2f2ad48e06ec4b500011976080621"

[[override]]
  name ="github.com/vishvananda/netlink"
  revision = "1e86b2bee5b6a7d377e4c02bb7f98209d6a7297c"
