---
version: 2
jobs:
  build:
    working_directory: /go/src/github.com/mobingilabs/go-modaemon
    docker:
      - image: golang:1.8.1
    steps:
      - checkout
      - run:
          name: save SHA to a file
          command: echo $CIRCLE_SHA1 > .circle-sha
      - restore_cache:
          key: godeps-{{ .Branch }}-{{ checksum "Gopkg.lock" }}
      - run:
          name: test and build maincli
          command: make cibuild
      - run:
          name: build addons
          command: make addon
      - save_cache:
          key: godeps-{{ .Branch }}-{{ checksum "Gopkg.lock" }}
          paths:
            - "/go/src"
      - store_artifacts:
          path: bin/
          destination: bin
      - save_cache:
          key: binaries-{{ checksum "~/.circle-sha" }}
          paths:
            - ~/bin
  deploy:
    machine:
        enabled: true
    working_directory: /tmp/workspace
    steps:
      - checkout
      - run:
          name: save SHA to a file
          command: echo $CIRCLE_SHA1 > .circle-sha
      - restore_cache:
          keys:
            - binaries-{{ checksum "~/.circle-sha" }}
      - run:
          name: build release infomation
          command: ./.circleci/release_info.sh
      - run:
          name: upload
          command: ./.circleci/upload_to_s3.sh

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
